name: lubaseriverpod
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1

  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  visibility_detector: ^0.4.0+2
  
  # REST API
  http: ^1.4.0
  dio: ^5.8.0+1
  retrofit: ^4.1.0

  # Store
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  # Utils 
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.4
  window_manager: ^0.5.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  go_router: ^15.1.3
  json_annotation: ^4.9.0
  logger: ^2.5.0
  responsive_framework: ^1.5.1
  pretty_dio_logger: ^1.4.0

  collection: ^1.19.1

  flutter_localizations:
    sdk: flutter
  intl: any
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.1
  analyzer: ^7.4.5

  build_runner: ^2.4.10
  retrofit_generator: ^9.2.0 
  json_serializable: ^6.9.5 
  flutter_gen_runner: ^5.10.0


flutter_gen:
  output: lib/resources/generated/
  integrations:
    flutter_svg: true
    rive: true
    lottie: true

  assets:
    outputs:
      style: camel-case

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/image/
    - assets/svg/

flutter_intl:
  enabled: true
  arb_dir: lib/resources/l10n
  output_dir: lib/resources/generated/